//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.SOAPReceptionMessage {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservicereception.service.com/", ConfigurationName="SOAPReceptionMessage.ReceptionEndpoint")]
    public interface ReceptionEndpoint {
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément key de l'espace de noms  n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webservicereception.service.com/ReceptionEndpoint/ReceptionOperationReques" +
            "t", ReplyAction="http://webservicereception.service.com/ReceptionEndpoint/ReceptionOperationRespon" +
            "se")]
        Backend.SOAPReceptionMessage.ReceptionOperationResponse ReceptionOperation(Backend.SOAPReceptionMessage.ReceptionOperationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservicereception.service.com/ReceptionEndpoint/ReceptionOperationReques" +
            "t", ReplyAction="http://webservicereception.service.com/ReceptionEndpoint/ReceptionOperationRespon" +
            "se")]
        System.Threading.Tasks.Task<Backend.SOAPReceptionMessage.ReceptionOperationResponse> ReceptionOperationAsync(Backend.SOAPReceptionMessage.ReceptionOperationRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément test de l'espace de noms  n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webservicereception.service.com/ReceptionEndpoint/ReceptionTestRequest", ReplyAction="http://webservicereception.service.com/ReceptionEndpoint/ReceptionTestResponse")]
        Backend.SOAPReceptionMessage.ReceptionTestResponse ReceptionTest(Backend.SOAPReceptionMessage.ReceptionTestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservicereception.service.com/ReceptionEndpoint/ReceptionTestRequest", ReplyAction="http://webservicereception.service.com/ReceptionEndpoint/ReceptionTestResponse")]
        System.Threading.Tasks.Task<Backend.SOAPReceptionMessage.ReceptionTestResponse> ReceptionTestAsync(Backend.SOAPReceptionMessage.ReceptionTestRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReceptionOperationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReceptionOperation", Namespace="http://webservicereception.service.com/", Order=0)]
        public Backend.SOAPReceptionMessage.ReceptionOperationRequestBody Body;
        
        public ReceptionOperationRequest() {
        }
        
        public ReceptionOperationRequest(Backend.SOAPReceptionMessage.ReceptionOperationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ReceptionOperationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public byte[] file;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string key;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string fileName;
        
        public ReceptionOperationRequestBody() {
        }
        
        public ReceptionOperationRequestBody(byte[] file, string key, string fileName) {
            this.file = file;
            this.key = key;
            this.fileName = fileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReceptionOperationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReceptionOperationResponse", Namespace="http://webservicereception.service.com/", Order=0)]
        public Backend.SOAPReceptionMessage.ReceptionOperationResponseBody Body;
        
        public ReceptionOperationResponse() {
        }
        
        public ReceptionOperationResponse(Backend.SOAPReceptionMessage.ReceptionOperationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ReceptionOperationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string receive;
        
        public ReceptionOperationResponseBody() {
        }
        
        public ReceptionOperationResponseBody(string receive) {
            this.receive = receive;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReceptionTestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReceptionTest", Namespace="http://webservicereception.service.com/", Order=0)]
        public Backend.SOAPReceptionMessage.ReceptionTestRequestBody Body;
        
        public ReceptionTestRequest() {
        }
        
        public ReceptionTestRequest(Backend.SOAPReceptionMessage.ReceptionTestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ReceptionTestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string test;
        
        public ReceptionTestRequestBody() {
        }
        
        public ReceptionTestRequestBody(string test) {
            this.test = test;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReceptionTestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReceptionTestResponse", Namespace="http://webservicereception.service.com/", Order=0)]
        public Backend.SOAPReceptionMessage.ReceptionTestResponseBody Body;
        
        public ReceptionTestResponse() {
        }
        
        public ReceptionTestResponse(Backend.SOAPReceptionMessage.ReceptionTestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ReceptionTestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string receiveTest;
        
        public ReceptionTestResponseBody() {
        }
        
        public ReceptionTestResponseBody(string receiveTest) {
            this.receiveTest = receiveTest;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ReceptionEndpointChannel : Backend.SOAPReceptionMessage.ReceptionEndpoint, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReceptionEndpointClient : System.ServiceModel.ClientBase<Backend.SOAPReceptionMessage.ReceptionEndpoint>, Backend.SOAPReceptionMessage.ReceptionEndpoint {
        
        public ReceptionEndpointClient() {
        }
        
        public ReceptionEndpointClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReceptionEndpointClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReceptionEndpointClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReceptionEndpointClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Backend.SOAPReceptionMessage.ReceptionOperationResponse Backend.SOAPReceptionMessage.ReceptionEndpoint.ReceptionOperation(Backend.SOAPReceptionMessage.ReceptionOperationRequest request) {
            return base.Channel.ReceptionOperation(request);
        }
        
        public string ReceptionOperation(byte[] file, string key, string fileName) {
            Backend.SOAPReceptionMessage.ReceptionOperationRequest inValue = new Backend.SOAPReceptionMessage.ReceptionOperationRequest();
            inValue.Body = new Backend.SOAPReceptionMessage.ReceptionOperationRequestBody();
            inValue.Body.file = file;
            inValue.Body.key = key;
            inValue.Body.fileName = fileName;
            Backend.SOAPReceptionMessage.ReceptionOperationResponse retVal = ((Backend.SOAPReceptionMessage.ReceptionEndpoint)(this)).ReceptionOperation(inValue);
            return retVal.Body.receive;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Backend.SOAPReceptionMessage.ReceptionOperationResponse> Backend.SOAPReceptionMessage.ReceptionEndpoint.ReceptionOperationAsync(Backend.SOAPReceptionMessage.ReceptionOperationRequest request) {
            return base.Channel.ReceptionOperationAsync(request);
        }
        
        public System.Threading.Tasks.Task<Backend.SOAPReceptionMessage.ReceptionOperationResponse> ReceptionOperationAsync(byte[] file, string key, string fileName) {
            Backend.SOAPReceptionMessage.ReceptionOperationRequest inValue = new Backend.SOAPReceptionMessage.ReceptionOperationRequest();
            inValue.Body = new Backend.SOAPReceptionMessage.ReceptionOperationRequestBody();
            inValue.Body.file = file;
            inValue.Body.key = key;
            inValue.Body.fileName = fileName;
            return ((Backend.SOAPReceptionMessage.ReceptionEndpoint)(this)).ReceptionOperationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Backend.SOAPReceptionMessage.ReceptionTestResponse Backend.SOAPReceptionMessage.ReceptionEndpoint.ReceptionTest(Backend.SOAPReceptionMessage.ReceptionTestRequest request) {
            return base.Channel.ReceptionTest(request);
        }
        
        public string ReceptionTest(string test) {
            Backend.SOAPReceptionMessage.ReceptionTestRequest inValue = new Backend.SOAPReceptionMessage.ReceptionTestRequest();
            inValue.Body = new Backend.SOAPReceptionMessage.ReceptionTestRequestBody();
            inValue.Body.test = test;
            Backend.SOAPReceptionMessage.ReceptionTestResponse retVal = ((Backend.SOAPReceptionMessage.ReceptionEndpoint)(this)).ReceptionTest(inValue);
            return retVal.Body.receiveTest;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Backend.SOAPReceptionMessage.ReceptionTestResponse> Backend.SOAPReceptionMessage.ReceptionEndpoint.ReceptionTestAsync(Backend.SOAPReceptionMessage.ReceptionTestRequest request) {
            return base.Channel.ReceptionTestAsync(request);
        }
        
        public System.Threading.Tasks.Task<Backend.SOAPReceptionMessage.ReceptionTestResponse> ReceptionTestAsync(string test) {
            Backend.SOAPReceptionMessage.ReceptionTestRequest inValue = new Backend.SOAPReceptionMessage.ReceptionTestRequest();
            inValue.Body = new Backend.SOAPReceptionMessage.ReceptionTestRequestBody();
            inValue.Body.test = test;
            return ((Backend.SOAPReceptionMessage.ReceptionEndpoint)(this)).ReceptionTestAsync(inValue);
        }
    }
}
